# MULTIPLE LINEAR REGRESSION MODEL

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.metrics import r2_score

In [2]:
os.chdir('C:\\Users\\atulk\\Desktop\\datasets')

In [3]:
strup = pd.read_csv('25 STARTSUP.csv')

In [5]:
strup.head()

R&D SPEND  ADMINISTRATION  MARKETING SPEND       STATE      PROFIT
0   165349.2       183631.12         71273.23    NEW YORK   231012.23
1   162342.3       153532.12        198322.22  CALIFORNIA   198322.12
2  1536232.4       753522.32        223212.23     FLORIDA  1983232.22
3  1447362.3       133737.13         73363.34    NEW YORK  1932211.32
4   135472.3       123333.23        123321.33     FLORIDA   239291.12

In [6]:
x=strup.iloc[:,:-1].values

In [7]:
y=strup.iloc[:,4].values

In [8]:
# convert string column state to numeric data

from sklearn.preprocessing import OneHotEncoder,LabelEncoder


In [9]:
labelenco = LabelEncoder()
x[:,3] =labelenco.fit_transform(x[:,3])

In [10]:
x

array([[165349.2, 183631.12, 71273.23, 2],
       [162342.3, 153532.12, 198322.22, 0],
       [1536232.4, 753522.32, 223212.23, 1],
       [1447362.3, 133737.13, 73363.34, 2],
       [135472.3, 123333.23, 123321.33, 1],
       [183423.3, 99876.32, 89701.11, 2],
       [1232433.4, 193733.33, 122322.12, 0],
       [123232.45, 12232.43, 100000.11, 1],
       [1846372.98, 1127383.32, 773543.43, 2],
       [238232.93, 28173.23, 34002.32, 1],
       [374323.1, 197364.32, 165022.22, 2],
       [1475743.03, 836343.44, 173633.32, 0],
       [1745372.3, 727662.43, 18432.22, 2],
       [1984637.32, 784632.32, 76432.12, 0],
       [1564932.23, 983624.32, 198764.33, 1],
       [187432.34, 87654.23, 98976.33, 0],
       [186483.22, 245373.32, 235463.33, 2],
       [1383433.1, 979835.32, 132021.44, 1],
       [1374033.37, 1645373.32, 980453.32, 2],
       [232223.43, 138463.23, 121012.22, 0],
       [573843.32, 123322.32, 98643.33, 2],
       [484833.43, 232212.32, 123321.55, 1],
       [214732.13199

In [11]:
onehot = OneHotEncoder(categorical_features=[3])
x = onehot.fit_transform(x).toarray()

C:\Users\atulk\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\atulk\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [12]:
pd.DataFrame(x)

0    1    2            3           4          5
0   0.0  0.0  1.0   165349.200   183631.12   71273.23
1   1.0  0.0  0.0   162342.300   153532.12  198322.22
2   0.0  1.0  0.0  1536232.400   753522.32  223212.23
3   0.0  0.0  1.0  1447362.300   133737.13   73363.34
4   0.0  1.0  0.0   135472.300   123333.23  123321.33
5   0.0  0.0  1.0   183423.300    99876.32   89701.11
6   1.0  0.0  0.0  1232433.400   193733.33  122322.12
7   0.0  1.0  0.0   123232.450    12232.43  100000.11
8   0.0  0.0  1.0  1846372.980  1127383.32  773543.43
9   0.0  1.0  0.0   238232.930    28173.23   34002.32
10  0.0  0.0  1.0   374323.100   197364.32  165022.22
11  1.0  0.0  0.0  1475743.030   836343.44  173633.32
12  0.0  0.0  1.0  1745372.300   727662.43   18432.22
13  1.0  0.0  0.0  1984637.320   784632.32   76432.12
14  0.0  1.0  0.0  1564932.230   983624.32  198764.33
15  1.0  0.0  0.0   187432.340    87654.23   98976.33
16  0.0  0.0  1.0   186483.220   245373.32  235463.33
17  0.0  1.0  0.0  1383433.100   979835.32  132021.44
18  0.0  0.0  1.0  1374033.370  1645373.32  980453.32
19  1.0  0.0  0.0   232223.430   138463.23  121012.22
20  0.0  0.0  1.0   573843.320   123322.32   98643.33
21  0.0  1.0  0.0   484833.430   232212.32  123321.55
22  0.0  1.0  0.0   214732.132   232223.21  132132.43
23  0.0  0.0  1.0   347332.320   138332.32   98743.32

In [13]:
from sklearn.model_selection import train_test_split
x_tr, x_te , y_tr , y_te =train_test_split(x,y,test_size=0.2)

In [14]:
y_te

array([1763523.12, 1835522.12, 1735351.32,  231012.23,  198322.12])

In [15]:
# lets make the model of linear regression

In [16]:
from sklearn.linear_model import LinearRegression
regrs = LinearRegression()
regrs.fit(x_tr , y_tr)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
y_pred = regrs.predict(x_te)

In [18]:
y_pred

array([2623111.68363973, 1470367.47759544, 1703077.30678813,
        -33293.55234824,  237776.37254354])

In [19]:
y_te

array([1763523.12, 1835522.12, 1735351.32,  231012.23,  198322.12])

In [20]:
# check r-square value

In [21]:
r2_score(y_pred,y_te)

0.8031214368087312

In [22]:
regrs.coef_

array([-4.24613189e+04,  1.41447001e+05, -9.89856825e+04,  1.36020070e+00,
       -7.55449676e-01,  1.54190339e+00])

In [23]:
regrs.intercept_

-130388.33278378763

# another method of regression model

In [24]:
import statsmodels.formula.api as sm


In [25]:
regressor_ols = sm.OLS(endog=y_tr , exog= x_tr).fit()


In [26]:
regressor_ols.summary()

C:\Users\atulk\Anaconda3\lib\site-packages\scipy\stats\stats.py:1416: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=19
  "anyway, n=%i" % int(n))


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.965
Model:                            OLS   Adj. R-squared:                  0.952
Method:                 Least Squares   F-statistic:                     72.25
Date:                Thu, 01 Aug 2019   Prob (F-statistic):           5.07e-09
Time:                        22:30:41   Log-Likelihood:                -251.12
No. Observations:                  19   AIC:                             514.2
Df Residuals:                      13   BIC:                             519.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1         -1.728e+05   1.09e+05     -1.580      0.138   -4.09e+05    6.36e+04
x2          1.106e+04   7.37e+04      0.150      0.883   -1.48e+05     1.7e+05
x3         -2.294e+05    9.3e+04     -2.465      0.028    -4.3e+05   -2.84e+04
x4             1.3602      0.118     11.535      0.000       1.105       1.615
x5            -0.7554      0.255     -2.963      0.011      -1.306      -0.205
x6             1.5419      0.385      4.009      0.001       0.711       2.373
==============================================================================
Omnibus:                        3.891   Durbin-Watson:                   2.235
Prob(Omnibus):                  0.143   Jarque-Bera (JB):                1.892
Skew:                          -0.376   Prob(JB):                        0.388
Kurtosis:                       4.350   Cond. No.                     3.88e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.88e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""